import { CenteredContainer } from "@/components";
import {
  Experience,
  FeaturedPosts,
  FeaturedProducts,
  Hero,
  OurServices,
  Reviews,
} from "@/components/home";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bandage | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <CenteredContainer>
        <Hero />
        <FeaturedProducts />
        <OurServices />
        <FeaturedPosts />
        <Reviews />
      </CenteredContainer>
      <Experience />
    </>
  );
}
